### PR TITLE
#11 - consensus algorithms described and compared

### PR DESCRIPTION
**Pull request by stepanvalyavskiy**
#11 - paxos, multi-paxos and raft algorithms described
raft compared with multi-paxos

### CODE REVIEW

**Comment by sunchao9** [comment]
I prefer `Raft` since it has less communications between nodes, and it avoid proposer conflicts by restricts the conditions of Leader election (which I think is more suitable for git operations).

**Review by g4s8 — CHANGES_REQUESTED** [review]
@stepanvalyavskiy I think we can create a new directory to store research summaries pages, e.g. `/docs` with sub README file with references to all pages and short summary

**Comment by sunchao9** [comment]
> @stepanvalyavskiy I think we can create a new directory to store research summaries pages, e.g. `/docs` with sub README file with references to all pages and short summary

Agree with you, we should create a `docs`, we can put the `user documentations`, `architrecture documentations`, `examples` etc. to it.

**Review by g4s8 — APPROVED** [review]
@stepanvalyavskiy thank

**Pull request merged**
