### PR TITLE
#41 Security analysis

### PR DESCRIPTION
**Pull request by stepanvalyavskiy**
#41 DeGitX security problems analysis based on `Secure routing for structured peer-to-peer overlay networks.`

### CODE REVIEW

**Review by g4s8 — CHANGES_REQUESTED** [review]
@stepanvalyavskiy let's use white paper to describe possible security issues and solution proposed. I think we can add new subsection under "Solution" and explain known problems and how we are going to solve them

**Comment by stepanvalyavskiy** [comment]
> @stepanvalyavskiy let's use white paper to describe possible security issues and solution proposed. I think we can add new subsection under "Solution" and explain known problems and how we are going to solve them

1st source from #41 is already a short summary of known overlay networks problems with possible solutions description. If we would describe known attacks it would be couple of pages copied from this doc.
@g4s8, do you mean I need to expand analysis somehow or only move it to white paper?

**Comment by g4s8** [comment]
> > @stepanvalyavskiy let's use white paper to describe possible security issues and solution proposed. I think we can add new subsection under "Solution" and explain known problems and how we are going to solve them
> 
> 1st source from #41 is already a short summary of known overlay networks problems with possible solutions description. If we would describe known attacks it would be couple of pages copied from this doc.
> @g4s8, do you mean I need to expand analysis somehow or only move it to white paper?

@stepanvalyavskiy yes, we need a summary from these research, for instance we can add something similar to the white paper:
> To prevent this kind of attacks (list of attacks applicable to our project) we use this approach (some approach), as researched in [1 (paper name)].
To prevent this security issue (another issue) we have this solution (another solution) as in [2 (another research)].
Etc

**Review by g4s8 — APPROVED** [review]
@stepanvalyavskiy thanks

**Pull request merged**
